train:
  _target_: src.datasets.AudioVisualDataset
  split: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AudioVisualDataset
  split: "val"
  instance_transforms: ${transforms.instance_transforms.inference}