train: []
inference: 
  - _target_: src.metrics.SISNRi
    name: "SI-SNRi" 
  - _target_: src.metrics.SISDRi
    name: "SI-SDRi"
  - _target_: src.metrics.PESQ
    name: "PESQ"
  - _target_: src.metrics.STOI
    name: "STOI"
