defaults:
  - model: tdfnet_16
  - writer: cometml
  - metrics: metrics
  - datasets: onebatchtest
  - dataloader: onebatchtest
  - transforms: normalize
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 1
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.SISNRLoss
trainer:
  log_step: 20
  n_epochs: 20
  epoch_len: 20
  device_tensors: ["mix", "targets", "mouths"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: cuda # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max val_SI-SNRi" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  max_grad_norm: 5
  use_amp: True
  amd_dtype: bf16
  seed: 1
lipreader_cfg: ${hydra:runtime.cwd}/src/lipreading_pretrained/config/lrw_resnet18_dctcn.json
